/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author Sergio
 */
public class Herramientas extends javax.swing.JPanel {
    
    //indica cual de las formas se va a dibujar
    public int formaElegida;
    //indica si la figura se tiene que pintar rellena o no
    public boolean relleno = false;
    public String textoEscrito = "";
    
    /**
     * Creates new form Herramientas
     */
    public Herramientas() {
        initComponents();
        jDialog1.setSize(330, 200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        textField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        confirmarBtn = new javax.swing.JButton();
        circulo = new javax.swing.JButton();
        rectangulo = new javax.swing.JButton();
        pentagono = new javax.swing.JButton();
        triangulo = new javax.swing.JButton();
        molino = new javax.swing.JButton();
        recta = new javax.swing.JButton();
        rellenoCheck = new javax.swing.JCheckBox();
        lapiz = new javax.swing.JButton();
        goma = new javax.swing.JButton();
        pipeta = new javax.swing.JButton();
        cubo = new javax.swing.JButton();

        jButton4.setText("jButton4");

        textField.setText("Ejemplo...");

        jLabel1.setText("Introduce el texto que quieres que aparezca en pantalla");

        confirmarBtn.setText("Confirmar");
        confirmarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textField)))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(confirmarBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmarBtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        circulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Circulo.png"))); // NOI18N
        circulo.setBorder(null);
        circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloActionPerformed(evt);
            }
        });

        rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cuadrado.png"))); // NOI18N
        rectangulo.setBorder(null);
        rectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectanguloActionPerformed(evt);
            }
        });

        pentagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pentagono.png"))); // NOI18N
        pentagono.setBorder(null);
        pentagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pentagonoActionPerformed(evt);
            }
        });

        triangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/triangulo.png"))); // NOI18N
        triangulo.setBorder(null);
        triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloActionPerformed(evt);
            }
        });

        molino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/estrella.png"))); // NOI18N
        molino.setToolTipText("");
        molino.setBorder(null);
        molino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                molinoActionPerformed(evt);
            }
        });

        recta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recta.png"))); // NOI18N
        recta.setBorder(null);
        recta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectaActionPerformed(evt);
            }
        });

        rellenoCheck.setText("Relleno");
        rellenoCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rellenoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rellenoCheckActionPerformed(evt);
            }
        });

        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lapiz.png"))); // NOI18N
        lapiz.setBorder(null);
        lapiz.setMaximumSize(new java.awt.Dimension(45, 45));
        lapiz.setMinimumSize(new java.awt.Dimension(45, 45));
        lapiz.setPreferredSize(new java.awt.Dimension(45, 45));
        lapiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapizActionPerformed(evt);
            }
        });

        goma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Goma.png"))); // NOI18N
        goma.setBorder(null);
        goma.setMaximumSize(new java.awt.Dimension(45, 45));
        goma.setMinimumSize(new java.awt.Dimension(45, 45));
        goma.setPreferredSize(new java.awt.Dimension(45, 45));
        goma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gomaActionPerformed(evt);
            }
        });

        pipeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pipeta.png"))); // NOI18N
        pipeta.setToolTipText("");
        pipeta.setBorder(null);
        pipeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pipetaActionPerformed(evt);
            }
        });

        cubo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letra (1) (1).png"))); // NOI18N
        cubo.setToolTipText("");
        cubo.setBorder(null);
        cubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lapiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(goma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pentagono, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(molino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(pipeta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cubo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rellenoCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lapiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pentagono, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(molino, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pipeta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cubo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rellenoCheck))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloActionPerformed
        formaElegida = 1;
    }//GEN-LAST:event_circuloActionPerformed

    private void rectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectanguloActionPerformed
        formaElegida = 4;
    }//GEN-LAST:event_rectanguloActionPerformed

    private void pentagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pentagonoActionPerformed
        formaElegida = 5;
    }//GEN-LAST:event_pentagonoActionPerformed

    private void trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloActionPerformed
        formaElegida = 3;
    }//GEN-LAST:event_trianguloActionPerformed

    private void molinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_molinoActionPerformed
        formaElegida = 256;
    }//GEN-LAST:event_molinoActionPerformed

    private void rectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectaActionPerformed
        formaElegida = 2;
    }//GEN-LAST:event_rectaActionPerformed

    private void rellenoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rellenoCheckActionPerformed
        relleno = rellenoCheck.isSelected();
    }//GEN-LAST:event_rellenoCheckActionPerformed

    private void lapizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapizActionPerformed
        formaElegida = 0;
    }//GEN-LAST:event_lapizActionPerformed

    private void gomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gomaActionPerformed
        formaElegida = 100;
    }//GEN-LAST:event_gomaActionPerformed

    private void pipetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pipetaActionPerformed
        formaElegida = 314;
    }//GEN-LAST:event_pipetaActionPerformed

    private void cuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuboActionPerformed
        formaElegida = 737;
        jDialog1.setVisible(true);
    }//GEN-LAST:event_cuboActionPerformed

    private void confirmarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarBtnActionPerformed
        textoEscrito = textField.getText();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_confirmarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circulo;
    private javax.swing.JButton confirmarBtn;
    private javax.swing.JButton cubo;
    private javax.swing.JButton goma;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lapiz;
    private javax.swing.JButton molino;
    private javax.swing.JButton pentagono;
    private javax.swing.JButton pipeta;
    private javax.swing.JButton recta;
    private javax.swing.JButton rectangulo;
    private javax.swing.JCheckBox rellenoCheck;
    private javax.swing.JTextField textField;
    private javax.swing.JButton triangulo;
    // End of variables declaration//GEN-END:variables
}
