/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Sergio
 */
public class PanelColores extends javax.swing.JPanel {
    
    public int tam1 = 5;
    public int tam2 = 5;
       
    public Color colorSeleccionado = Color.black;
    /**
     * Creates new form PanelColores
     */
    public PanelColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rojo = new javax.swing.JLabel();
        negro = new javax.swing.JLabel();
        verde = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        blanco = new javax.swing.JLabel();
        gris = new javax.swing.JLabel();
        grisClaro = new javax.swing.JLabel();
        granate = new javax.swing.JLabel();
        mostaza = new javax.swing.JLabel();
        verdeOscuro = new javax.swing.JLabel();
        cian = new javax.swing.JLabel();
        cianOscuro = new javax.swing.JLabel();
        magenta = new javax.swing.JLabel();
        morado = new javax.swing.JLabel();
        mantequilla = new javax.swing.JLabel();
        manteca = new javax.swing.JLabel();
        menta = new javax.swing.JLabel();
        hoja = new javax.swing.JLabel();
        cielo = new javax.swing.JLabel();
        cieloNublado = new javax.swing.JLabel();
        naranja = new javax.swing.JLabel();
        marron = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fieldTam = new javax.swing.JTextField();
        rosita = new javax.swing.JLabel();
        moradoOscuro = new javax.swing.JLabel();
        radioactivo = new javax.swing.JLabel();
        mugre = new javax.swing.JLabel();
        nube = new javax.swing.JLabel();
        oceano = new javax.swing.JLabel();
        infierno = new javax.swing.JLabel();
        cerdo = new javax.swing.JLabel();
        donal = new javax.swing.JLabel();
        defecacion = new javax.swing.JLabel();
        moco = new javax.swing.JLabel();
        swamp = new javax.swing.JLabel();
        bloque = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cordeX = new javax.swing.JLabel();
        cordeY = new javax.swing.JLabel();

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rojo.setMaximumSize(new java.awt.Dimension(20, 20));
        rojo.setMinimumSize(new java.awt.Dimension(20, 20));
        rojo.setOpaque(true);
        rojo.setPreferredSize(new java.awt.Dimension(20, 20));
        rojo.setRequestFocusEnabled(false);
        rojo.setVerifyInputWhenFocusTarget(false);
        rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rojoMouseClicked(evt);
            }
        });

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        negro.setMaximumSize(new java.awt.Dimension(20, 20));
        negro.setMinimumSize(new java.awt.Dimension(20, 20));
        negro.setOpaque(true);
        negro.setPreferredSize(new java.awt.Dimension(20, 20));
        negro.setRequestFocusEnabled(false);
        negro.setVerifyInputWhenFocusTarget(false);
        negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negroMouseClicked(evt);
            }
        });

        verde.setBackground(new java.awt.Color(0, 204, 0));
        verde.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verde.setMaximumSize(new java.awt.Dimension(20, 20));
        verde.setMinimumSize(new java.awt.Dimension(20, 20));
        verde.setOpaque(true);
        verde.setPreferredSize(new java.awt.Dimension(20, 20));
        verde.setRequestFocusEnabled(false);
        verde.setVerifyInputWhenFocusTarget(false);
        verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verdeMouseClicked(evt);
            }
        });

        amarillo.setBackground(new java.awt.Color(255, 255, 0));
        amarillo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        amarillo.setMaximumSize(new java.awt.Dimension(20, 20));
        amarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        amarillo.setOpaque(true);
        amarillo.setPreferredSize(new java.awt.Dimension(20, 20));
        amarillo.setRequestFocusEnabled(false);
        amarillo.setVerifyInputWhenFocusTarget(false);
        amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amarilloMouseClicked(evt);
            }
        });

        blanco.setBackground(new java.awt.Color(255, 255, 255));
        blanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        blanco.setMaximumSize(new java.awt.Dimension(20, 20));
        blanco.setMinimumSize(new java.awt.Dimension(20, 20));
        blanco.setOpaque(true);
        blanco.setPreferredSize(new java.awt.Dimension(20, 20));
        blanco.setRequestFocusEnabled(false);
        blanco.setVerifyInputWhenFocusTarget(false);
        blanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blancoMouseClicked(evt);
            }
        });

        gris.setBackground(new java.awt.Color(102, 102, 102));
        gris.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gris.setMaximumSize(new java.awt.Dimension(20, 20));
        gris.setMinimumSize(new java.awt.Dimension(20, 20));
        gris.setOpaque(true);
        gris.setPreferredSize(new java.awt.Dimension(20, 20));
        gris.setRequestFocusEnabled(false);
        gris.setVerifyInputWhenFocusTarget(false);
        gris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grisMouseClicked(evt);
            }
        });

        grisClaro.setBackground(new java.awt.Color(204, 204, 204));
        grisClaro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        grisClaro.setMaximumSize(new java.awt.Dimension(20, 20));
        grisClaro.setMinimumSize(new java.awt.Dimension(20, 20));
        grisClaro.setOpaque(true);
        grisClaro.setPreferredSize(new java.awt.Dimension(20, 20));
        grisClaro.setRequestFocusEnabled(false);
        grisClaro.setVerifyInputWhenFocusTarget(false);
        grisClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grisClaroMouseClicked(evt);
            }
        });

        granate.setBackground(new java.awt.Color(153, 0, 0));
        granate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        granate.setMaximumSize(new java.awt.Dimension(20, 20));
        granate.setMinimumSize(new java.awt.Dimension(20, 20));
        granate.setOpaque(true);
        granate.setPreferredSize(new java.awt.Dimension(20, 20));
        granate.setRequestFocusEnabled(false);
        granate.setVerifyInputWhenFocusTarget(false);
        granate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                granateMouseClicked(evt);
            }
        });

        mostaza.setBackground(new java.awt.Color(153, 153, 0));
        mostaza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mostaza.setMaximumSize(new java.awt.Dimension(20, 20));
        mostaza.setMinimumSize(new java.awt.Dimension(20, 20));
        mostaza.setOpaque(true);
        mostaza.setPreferredSize(new java.awt.Dimension(20, 20));
        mostaza.setRequestFocusEnabled(false);
        mostaza.setVerifyInputWhenFocusTarget(false);
        mostaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostazaMouseClicked(evt);
            }
        });

        verdeOscuro.setBackground(new java.awt.Color(0, 102, 0));
        verdeOscuro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verdeOscuro.setMaximumSize(new java.awt.Dimension(20, 20));
        verdeOscuro.setMinimumSize(new java.awt.Dimension(20, 20));
        verdeOscuro.setOpaque(true);
        verdeOscuro.setPreferredSize(new java.awt.Dimension(20, 20));
        verdeOscuro.setRequestFocusEnabled(false);
        verdeOscuro.setVerifyInputWhenFocusTarget(false);
        verdeOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verdeOscuroMouseClicked(evt);
            }
        });

        cian.setBackground(new java.awt.Color(51, 255, 255));
        cian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cian.setMaximumSize(new java.awt.Dimension(20, 20));
        cian.setMinimumSize(new java.awt.Dimension(20, 20));
        cian.setOpaque(true);
        cian.setPreferredSize(new java.awt.Dimension(20, 20));
        cian.setRequestFocusEnabled(false);
        cian.setVerifyInputWhenFocusTarget(false);
        cian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cianMouseClicked(evt);
            }
        });

        cianOscuro.setBackground(new java.awt.Color(0, 153, 153));
        cianOscuro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cianOscuro.setMaximumSize(new java.awt.Dimension(20, 20));
        cianOscuro.setMinimumSize(new java.awt.Dimension(20, 20));
        cianOscuro.setOpaque(true);
        cianOscuro.setPreferredSize(new java.awt.Dimension(20, 20));
        cianOscuro.setRequestFocusEnabled(false);
        cianOscuro.setVerifyInputWhenFocusTarget(false);
        cianOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cianOscuroMouseClicked(evt);
            }
        });

        magenta.setBackground(new java.awt.Color(255, 0, 204));
        magenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        magenta.setMaximumSize(new java.awt.Dimension(20, 20));
        magenta.setMinimumSize(new java.awt.Dimension(20, 20));
        magenta.setOpaque(true);
        magenta.setPreferredSize(new java.awt.Dimension(20, 20));
        magenta.setRequestFocusEnabled(false);
        magenta.setVerifyInputWhenFocusTarget(false);
        magenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                magentaMouseClicked(evt);
            }
        });

        morado.setBackground(new java.awt.Color(102, 0, 102));
        morado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        morado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        morado.setMaximumSize(new java.awt.Dimension(20, 20));
        morado.setMinimumSize(new java.awt.Dimension(20, 20));
        morado.setOpaque(true);
        morado.setPreferredSize(new java.awt.Dimension(20, 20));
        morado.setRequestFocusEnabled(false);
        morado.setVerifyInputWhenFocusTarget(false);
        morado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moradoMouseClicked(evt);
            }
        });

        mantequilla.setBackground(new java.awt.Color(255, 255, 153));
        mantequilla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mantequilla.setMaximumSize(new java.awt.Dimension(20, 20));
        mantequilla.setMinimumSize(new java.awt.Dimension(20, 20));
        mantequilla.setOpaque(true);
        mantequilla.setPreferredSize(new java.awt.Dimension(20, 20));
        mantequilla.setRequestFocusEnabled(false);
        mantequilla.setVerifyInputWhenFocusTarget(false);
        mantequilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mantequillaMouseClicked(evt);
            }
        });

        manteca.setBackground(new java.awt.Color(220, 220, 144));
        manteca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manteca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        manteca.setMaximumSize(new java.awt.Dimension(20, 20));
        manteca.setMinimumSize(new java.awt.Dimension(20, 20));
        manteca.setOpaque(true);
        manteca.setPreferredSize(new java.awt.Dimension(20, 20));
        manteca.setRequestFocusEnabled(false);
        manteca.setVerifyInputWhenFocusTarget(false);
        manteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mantecaMouseClicked(evt);
            }
        });

        menta.setBackground(new java.awt.Color(102, 255, 153));
        menta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menta.setMaximumSize(new java.awt.Dimension(20, 20));
        menta.setMinimumSize(new java.awt.Dimension(20, 20));
        menta.setOpaque(true);
        menta.setPreferredSize(new java.awt.Dimension(20, 20));
        menta.setRequestFocusEnabled(false);
        menta.setVerifyInputWhenFocusTarget(false);
        menta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentaMouseClicked(evt);
            }
        });

        hoja.setBackground(new java.awt.Color(0, 102, 51));
        hoja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hoja.setMaximumSize(new java.awt.Dimension(20, 20));
        hoja.setMinimumSize(new java.awt.Dimension(20, 20));
        hoja.setOpaque(true);
        hoja.setPreferredSize(new java.awt.Dimension(20, 20));
        hoja.setRequestFocusEnabled(false);
        hoja.setVerifyInputWhenFocusTarget(false);
        hoja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hojaMouseClicked(evt);
            }
        });

        cielo.setBackground(new java.awt.Color(204, 255, 204));
        cielo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cielo.setMaximumSize(new java.awt.Dimension(20, 20));
        cielo.setMinimumSize(new java.awt.Dimension(20, 20));
        cielo.setOpaque(true);
        cielo.setPreferredSize(new java.awt.Dimension(20, 20));
        cielo.setRequestFocusEnabled(false);
        cielo.setVerifyInputWhenFocusTarget(false);
        cielo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cieloMouseClicked(evt);
            }
        });

        cieloNublado.setBackground(new java.awt.Color(0, 102, 102));
        cieloNublado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cieloNublado.setMaximumSize(new java.awt.Dimension(20, 20));
        cieloNublado.setMinimumSize(new java.awt.Dimension(20, 20));
        cieloNublado.setOpaque(true);
        cieloNublado.setPreferredSize(new java.awt.Dimension(20, 20));
        cieloNublado.setRequestFocusEnabled(false);
        cieloNublado.setVerifyInputWhenFocusTarget(false);
        cieloNublado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cieloNubladoMouseClicked(evt);
            }
        });

        naranja.setBackground(new java.awt.Color(255, 102, 0));
        naranja.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        naranja.setMaximumSize(new java.awt.Dimension(20, 20));
        naranja.setMinimumSize(new java.awt.Dimension(20, 20));
        naranja.setOpaque(true);
        naranja.setPreferredSize(new java.awt.Dimension(20, 20));
        naranja.setRequestFocusEnabled(false);
        naranja.setVerifyInputWhenFocusTarget(false);
        naranja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                naranjaMouseClicked(evt);
            }
        });

        marron.setBackground(new java.awt.Color(153, 51, 0));
        marron.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        marron.setMaximumSize(new java.awt.Dimension(20, 20));
        marron.setMinimumSize(new java.awt.Dimension(20, 20));
        marron.setOpaque(true);
        marron.setPreferredSize(new java.awt.Dimension(20, 20));
        marron.setRequestFocusEnabled(false);
        marron.setVerifyInputWhenFocusTarget(false);
        marron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marronMouseClicked(evt);
            }
        });

        jLabel1.setText("Tamaño:");

        fieldTam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldTam.setText("3");
        fieldTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTamActionPerformed(evt);
            }
        });

        rosita.setBackground(new java.awt.Color(255, 144, 199));
        rosita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rosita.setMaximumSize(new java.awt.Dimension(20, 20));
        rosita.setMinimumSize(new java.awt.Dimension(20, 20));
        rosita.setOpaque(true);
        rosita.setPreferredSize(new java.awt.Dimension(20, 20));
        rosita.setRequestFocusEnabled(false);
        rosita.setVerifyInputWhenFocusTarget(false);
        rosita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rositaMouseClicked(evt);
            }
        });

        moradoOscuro.setBackground(new java.awt.Color(51, 0, 51));
        moradoOscuro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        moradoOscuro.setMaximumSize(new java.awt.Dimension(20, 20));
        moradoOscuro.setMinimumSize(new java.awt.Dimension(20, 20));
        moradoOscuro.setOpaque(true);
        moradoOscuro.setPreferredSize(new java.awt.Dimension(20, 20));
        moradoOscuro.setRequestFocusEnabled(false);
        moradoOscuro.setVerifyInputWhenFocusTarget(false);
        moradoOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moradoOscuroMouseClicked(evt);
            }
        });

        radioactivo.setBackground(new java.awt.Color(153, 255, 0));
        radioactivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        radioactivo.setMaximumSize(new java.awt.Dimension(20, 20));
        radioactivo.setMinimumSize(new java.awt.Dimension(20, 20));
        radioactivo.setOpaque(true);
        radioactivo.setPreferredSize(new java.awt.Dimension(20, 20));
        radioactivo.setRequestFocusEnabled(false);
        radioactivo.setVerifyInputWhenFocusTarget(false);
        radioactivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radioactivoMouseClicked(evt);
            }
        });

        mugre.setBackground(new java.awt.Color(102, 102, 0));
        mugre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mugre.setMaximumSize(new java.awt.Dimension(20, 20));
        mugre.setMinimumSize(new java.awt.Dimension(20, 20));
        mugre.setOpaque(true);
        mugre.setPreferredSize(new java.awt.Dimension(20, 20));
        mugre.setRequestFocusEnabled(false);
        mugre.setVerifyInputWhenFocusTarget(false);
        mugre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mugreMouseClicked(evt);
            }
        });

        nube.setBackground(new java.awt.Color(204, 204, 255));
        nube.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nube.setMaximumSize(new java.awt.Dimension(20, 20));
        nube.setMinimumSize(new java.awt.Dimension(20, 20));
        nube.setOpaque(true);
        nube.setPreferredSize(new java.awt.Dimension(20, 20));
        nube.setRequestFocusEnabled(false);
        nube.setVerifyInputWhenFocusTarget(false);
        nube.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nubeMouseClicked(evt);
            }
        });

        oceano.setBackground(new java.awt.Color(51, 0, 204));
        oceano.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        oceano.setMaximumSize(new java.awt.Dimension(20, 20));
        oceano.setMinimumSize(new java.awt.Dimension(20, 20));
        oceano.setOpaque(true);
        oceano.setPreferredSize(new java.awt.Dimension(20, 20));
        oceano.setRequestFocusEnabled(false);
        oceano.setVerifyInputWhenFocusTarget(false);
        oceano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oceanoMouseClicked(evt);
            }
        });

        infierno.setBackground(new java.awt.Color(255, 51, 51));
        infierno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        infierno.setMaximumSize(new java.awt.Dimension(20, 20));
        infierno.setMinimumSize(new java.awt.Dimension(20, 20));
        infierno.setOpaque(true);
        infierno.setPreferredSize(new java.awt.Dimension(20, 20));
        infierno.setRequestFocusEnabled(false);
        infierno.setVerifyInputWhenFocusTarget(false);
        infierno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infiernoMouseClicked(evt);
            }
        });

        cerdo.setBackground(new java.awt.Color(255, 153, 153));
        cerdo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerdo.setMaximumSize(new java.awt.Dimension(20, 20));
        cerdo.setMinimumSize(new java.awt.Dimension(20, 20));
        cerdo.setOpaque(true);
        cerdo.setPreferredSize(new java.awt.Dimension(20, 20));
        cerdo.setRequestFocusEnabled(false);
        cerdo.setVerifyInputWhenFocusTarget(false);
        cerdo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerdoMouseClicked(evt);
            }
        });

        donal.setBackground(new java.awt.Color(255, 153, 51));
        donal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        donal.setMaximumSize(new java.awt.Dimension(20, 20));
        donal.setMinimumSize(new java.awt.Dimension(20, 20));
        donal.setOpaque(true);
        donal.setPreferredSize(new java.awt.Dimension(20, 20));
        donal.setRequestFocusEnabled(false);
        donal.setVerifyInputWhenFocusTarget(false);
        donal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donalMouseClicked(evt);
            }
        });

        defecacion.setBackground(new java.awt.Color(153, 102, 0));
        defecacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        defecacion.setMaximumSize(new java.awt.Dimension(20, 20));
        defecacion.setMinimumSize(new java.awt.Dimension(20, 20));
        defecacion.setOpaque(true);
        defecacion.setPreferredSize(new java.awt.Dimension(20, 20));
        defecacion.setRequestFocusEnabled(false);
        defecacion.setVerifyInputWhenFocusTarget(false);
        defecacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                defecacionMouseClicked(evt);
            }
        });

        moco.setBackground(new java.awt.Color(56, 220, 109));
        moco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        moco.setMaximumSize(new java.awt.Dimension(20, 20));
        moco.setMinimumSize(new java.awt.Dimension(20, 20));
        moco.setOpaque(true);
        moco.setPreferredSize(new java.awt.Dimension(20, 20));
        moco.setRequestFocusEnabled(false);
        moco.setVerifyInputWhenFocusTarget(false);
        moco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mocoMouseClicked(evt);
            }
        });

        swamp.setBackground(new java.awt.Color(153, 203, 91));
        swamp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        swamp.setMaximumSize(new java.awt.Dimension(20, 20));
        swamp.setMinimumSize(new java.awt.Dimension(20, 20));
        swamp.setOpaque(true);
        swamp.setPreferredSize(new java.awt.Dimension(20, 20));
        swamp.setRequestFocusEnabled(false);
        swamp.setVerifyInputWhenFocusTarget(false);
        swamp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                swampMouseClicked(evt);
            }
        });

        bloque.setBackground(new java.awt.Color(0, 0, 0));
        bloque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bloque.setOpaque(true);

        jLabel2.setText("Coordenadas:");

        cordeX.setBackground(new java.awt.Color(255, 255, 255));
        cordeX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cordeX.setText("0");
        cordeX.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cordeX.setOpaque(true);

        cordeY.setBackground(new java.awt.Color(255, 255, 255));
        cordeY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cordeY.setText("0");
        cordeY.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cordeY.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bloque, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(negro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(granate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verdeOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cianOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(morado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cieloNublado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moradoOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mugre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oceano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infierno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defecacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(swamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grisClaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amarillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mantequilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cielo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rosita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nube, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cordeX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cordeY, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bloque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(negro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(grisClaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(granate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cianOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verdeOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mostaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(morado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amarillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(magenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mantequilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(menta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cieloNublado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cielo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(marron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naranja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(moradoOscuro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rosita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mugre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioactivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oceano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infierno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nube, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(defecacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(donal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(swamp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldTam)
                            .addComponent(jLabel2)
                            .addComponent(cordeX, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cordeY, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    //En todos los siguientes voids se castea el evt como JLabel y se le cambia el
    //color a la seleccion con el que tiene el Label de fondo
    
    private void rojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rojoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rojoMouseClicked

    private void negroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_negroMouseClicked

    private void verdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeMouseClicked

    private void amarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amarilloMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_amarilloMouseClicked

    private void blancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_blancoMouseClicked

    private void grisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_grisMouseClicked

    private void grisClaroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisClaroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_grisClaroMouseClicked

    private void granateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_granateMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_granateMouseClicked

    private void mostazaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostazaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mostazaMouseClicked

    private void verdeOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeOscuroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_verdeOscuroMouseClicked

    private void cianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cianMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_cianMouseClicked

    private void cianOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cianOscuroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_cianOscuroMouseClicked

    private void magentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_magentaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_magentaMouseClicked

    private void moradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moradoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_moradoMouseClicked

    private void mantequillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mantequillaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mantequillaMouseClicked

    private void mantecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mantecaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mantecaMouseClicked

    private void mentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mentaMouseClicked

    private void hojaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hojaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_hojaMouseClicked

    private void cieloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cieloMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_cieloMouseClicked

    private void cieloNubladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cieloNubladoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_cieloNubladoMouseClicked

    private void naranjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_naranjaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_naranjaMouseClicked

    private void marronMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marronMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_marronMouseClicked

    private void fieldTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTamActionPerformed
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_fieldTamActionPerformed

    private void rositaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rositaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_rositaMouseClicked

    private void moradoOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moradoOscuroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_moradoOscuroMouseClicked

    private void radioactivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioactivoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_radioactivoMouseClicked

    private void mugreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mugreMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mugreMouseClicked

    private void nubeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nubeMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_nubeMouseClicked

    private void oceanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oceanoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_oceanoMouseClicked

    private void infiernoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infiernoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_infiernoMouseClicked

    private void cerdoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerdoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_cerdoMouseClicked

    private void donalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donalMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_donalMouseClicked

    private void defecacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defecacionMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_defecacionMouseClicked

    private void mocoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mocoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_mocoMouseClicked

    private void swampMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swampMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        cambiaTamaño();
        bloque.setBackground(colorSeleccionado);
    }//GEN-LAST:event_swampMouseClicked

    public void cambiaTamaño(){
        int tamaño = Integer.parseInt(fieldTam.getText());
        tam1 = tamaño;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarillo;
    private javax.swing.JLabel blanco;
    public javax.swing.JLabel bloque;
    private javax.swing.JLabel cerdo;
    private javax.swing.JLabel cian;
    private javax.swing.JLabel cianOscuro;
    private javax.swing.JLabel cielo;
    private javax.swing.JLabel cieloNublado;
    public javax.swing.JLabel cordeX;
    public javax.swing.JLabel cordeY;
    private javax.swing.JLabel defecacion;
    private javax.swing.JLabel donal;
    private javax.swing.JTextField fieldTam;
    private javax.swing.JLabel granate;
    private javax.swing.JLabel gris;
    private javax.swing.JLabel grisClaro;
    private javax.swing.JLabel hoja;
    private javax.swing.JLabel infierno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel magenta;
    private javax.swing.JLabel manteca;
    private javax.swing.JLabel mantequilla;
    private javax.swing.JLabel marron;
    private javax.swing.JLabel menta;
    private javax.swing.JLabel moco;
    private javax.swing.JLabel morado;
    private javax.swing.JLabel moradoOscuro;
    private javax.swing.JLabel mostaza;
    private javax.swing.JLabel mugre;
    private javax.swing.JLabel naranja;
    private javax.swing.JLabel negro;
    private javax.swing.JLabel nube;
    private javax.swing.JLabel oceano;
    private javax.swing.JLabel radioactivo;
    private javax.swing.JLabel rojo;
    private javax.swing.JLabel rosita;
    private javax.swing.JLabel swamp;
    private javax.swing.JLabel verde;
    private javax.swing.JLabel verdeOscuro;
    // End of variables declaration//GEN-END:variables
}
