/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Sergio
 */
public class PanelColores extends javax.swing.JPanel {
    
    public int tam1 = 5;
    public int tam2 = 5;
       
    public Color colorSeleccionado = Color.black;
    /**
     * Creates new form PanelColores
     */
    public PanelColores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rojo = new javax.swing.JLabel();
        negro = new javax.swing.JLabel();
        azul = new javax.swing.JLabel();
        verde = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        magenta = new javax.swing.JLabel();
        blanco = new javax.swing.JLabel();
        gris = new javax.swing.JLabel();
        grisClaro = new javax.swing.JLabel();
        granate = new javax.swing.JLabel();
        mostaza = new javax.swing.JLabel();
        verdeOscuro = new javax.swing.JLabel();

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.setMaximumSize(new java.awt.Dimension(20, 20));
        rojo.setMinimumSize(new java.awt.Dimension(20, 20));
        rojo.setOpaque(true);
        rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rojoMouseClicked(evt);
            }
        });

        negro.setBackground(new java.awt.Color(0, 0, 0));
        negro.setOpaque(true);
        negro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                negroMouseClicked(evt);
            }
        });

        azul.setBackground(new java.awt.Color(0, 0, 255));
        azul.setMaximumSize(new java.awt.Dimension(20, 20));
        azul.setMinimumSize(new java.awt.Dimension(20, 20));
        azul.setOpaque(true);
        azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                azulMouseClicked(evt);
            }
        });

        verde.setBackground(new java.awt.Color(0, 204, 0));
        verde.setMaximumSize(new java.awt.Dimension(20, 20));
        verde.setMinimumSize(new java.awt.Dimension(20, 20));
        verde.setOpaque(true);
        verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verdeMouseClicked(evt);
            }
        });

        amarillo.setBackground(new java.awt.Color(255, 255, 0));
        amarillo.setMaximumSize(new java.awt.Dimension(20, 20));
        amarillo.setMinimumSize(new java.awt.Dimension(20, 20));
        amarillo.setOpaque(true);
        amarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                amarilloMouseClicked(evt);
            }
        });

        magenta.setBackground(new java.awt.Color(255, 0, 204));
        magenta.setMaximumSize(new java.awt.Dimension(20, 20));
        magenta.setMinimumSize(new java.awt.Dimension(20, 20));
        magenta.setOpaque(true);
        magenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                magentaMouseClicked(evt);
            }
        });

        blanco.setBackground(new java.awt.Color(255, 255, 255));
        blanco.setOpaque(true);
        blanco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blancoMouseClicked(evt);
            }
        });

        gris.setBackground(new java.awt.Color(102, 102, 102));
        gris.setOpaque(true);
        gris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grisMouseClicked(evt);
            }
        });

        grisClaro.setBackground(new java.awt.Color(204, 204, 204));
        grisClaro.setOpaque(true);
        grisClaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grisClaroMouseClicked(evt);
            }
        });

        granate.setBackground(new java.awt.Color(153, 0, 0));
        granate.setMaximumSize(new java.awt.Dimension(20, 20));
        granate.setMinimumSize(new java.awt.Dimension(20, 20));
        granate.setOpaque(true);
        granate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                granateMouseClicked(evt);
            }
        });

        mostaza.setBackground(new java.awt.Color(153, 153, 0));
        mostaza.setMaximumSize(new java.awt.Dimension(20, 20));
        mostaza.setMinimumSize(new java.awt.Dimension(20, 20));
        mostaza.setOpaque(true);
        mostaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostazaMouseClicked(evt);
            }
        });

        verdeOscuro.setBackground(new java.awt.Color(0, 102, 0));
        verdeOscuro.setMaximumSize(new java.awt.Dimension(20, 20));
        verdeOscuro.setMinimumSize(new java.awt.Dimension(20, 20));
        verdeOscuro.setOpaque(true);
        verdeOscuro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verdeOscuroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(negro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gris, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(granate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostaza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verdeOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(blanco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grisClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(verde, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(magenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addComponent(azul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(azul, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(negro, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(gris, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(magenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blanco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(grisClaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(granate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rojo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verdeOscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostaza, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amarillo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rojoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_rojoMouseClicked

    private void negroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_negroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_negroMouseClicked

    private void azulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azulMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_azulMouseClicked

    private void verdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_verdeMouseClicked

    private void amarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_amarilloMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_amarilloMouseClicked

    private void magentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_magentaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_magentaMouseClicked

    private void blancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blancoMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 10;
        tam2 = 10;
    }//GEN-LAST:event_blancoMouseClicked

    private void grisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_grisMouseClicked

    private void grisClaroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grisClaroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_grisClaroMouseClicked

    private void granateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_granateMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_granateMouseClicked

    private void mostazaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostazaMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_mostazaMouseClicked

    private void verdeOscuroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verdeOscuroMouseClicked
        JLabel s = (JLabel) evt.getSource();
        colorSeleccionado = s.getBackground();
        tam1 = 5;
        tam2 = 5;
    }//GEN-LAST:event_verdeOscuroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarillo;
    private javax.swing.JLabel azul;
    private javax.swing.JLabel blanco;
    private javax.swing.JLabel granate;
    private javax.swing.JLabel gris;
    private javax.swing.JLabel grisClaro;
    private javax.swing.JLabel magenta;
    private javax.swing.JLabel mostaza;
    private javax.swing.JLabel negro;
    private javax.swing.JLabel rojo;
    private javax.swing.JLabel verde;
    private javax.swing.JLabel verdeOscuro;
    // End of variables declaration//GEN-END:variables
}
