/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import codigo.formas.Circulo;
import codigo.formas.Cuadrado;
import codigo.formas.Estrella;
import codigo.formas.Forma;
import codigo.formas.Pentagono;
import codigo.formas.Recta;
import codigo.formas.Triangulo;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Sergio
 */
public class VentanaPaint extends javax.swing.JFrame {

    BufferedImage buffer, buffer2 = null;
    Graphics2D bufferGraphics, bufferGraphics2 , jpanelGraphics = null;
    Circulo miCirculo = null;
    Forma miForma = new Forma(-1, -1, 0, Color.WHITE, false); //para que la forma no de error
    Random random = new Random();
    
    /**
     * Creates new form VentanaPaint
     */
    public VentanaPaint() {
        initComponents();
        inicializaBuffers();
        jDialog1.setSize(630, 450);
    }
    
    private void inicializaBuffers(){
        //creo una imagen del mismo ancho y alto que el jPanel1
        buffer = (BufferedImage) jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
        buffer2 = (BufferedImage) jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
        //creo una imagen modificable
        bufferGraphics = buffer.createGraphics();
        bufferGraphics2 = buffer2.createGraphics();
        //inicializo el buffer para que pinte de blanco entero
        bufferGraphics.setColor(Color.WHITE);
        bufferGraphics.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        
        bufferGraphics2.setColor(Color.WHITE);
        bufferGraphics2.fillRect(0, 0, jPanel1.getWidth(), jPanel1.getHeight());
        
        //enlazamos el jPanel1 con el jPanelGraphics
        jpanelGraphics = (Graphics2D) jPanel1.getGraphics();
        
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        
        //pinto el buffer sobre el jPanel
        jpanelGraphics.drawImage(buffer, 0, 0, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        cancelar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jDialog2 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog3 = new javax.swing.JDialog();
        campoDtexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelColores2 = new codigo.PanelColores();
        herramientas1 = new codigo.Herramientas();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        guardarMenu = new javax.swing.JMenuItem();
        importar = new javax.swing.JMenuItem();
        nuevo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar)
                .addGap(145, 145, 145))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(guardar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("Introduce el texto que quieras poner en pantalla");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Confirmar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addComponent(campoDtexto)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoDtexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paint98");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/paintico.jpg")).getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        jButton1.setText("Más Colores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        guardarMenu.setText("Guardar");
        guardarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuActionPerformed(evt);
            }
        });
        jMenu1.add(guardarMenu);

        importar.setText("Importar");
        importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarActionPerformed(evt);
            }
        });
        jMenu1.add(importar);

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jMenu1.add(nuevo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(herramientas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelColores2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(herramientas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelColores2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        bufferGraphics.drawImage(buffer2, 0, 0, null);
        /*String equis = Integer.toString(evt.getX());
        String yyy = Integer.toString(evt.getY());
        panelColores2.cordeX.setText(equis);
        panelColores2.cordeY.setText(yyy);*/
        switch(herramientas1.formaElegida){
            case 0 :
                //Dibujo libre - Lapiz
                //Varía tanto el color como el tamaño
                panelColores2.cambiaTamaño();
                bufferGraphics2.setColor(panelColores2.colorSeleccionado);
                bufferGraphics2.fillOval(evt.getX(), evt.getY(), panelColores2.tam1, panelColores2.tam1);
                break;
            case 10 :
                //Spray
                //Una variables con aleatorios para darle ese efecto de dispersión
                //Por el resto de cosas es igual que el anterior
                int parseX = evt.getX() + randomiz(-7, 7);
                int parseY = evt.getY() + randomiz(-7, 7);
                int parseX2 = evt.getX() + randomiz(-7, 7);
                int parseY2 = evt.getY() + randomiz(-7, 7);
                panelColores2.cambiaTamaño();
                bufferGraphics2.setColor(panelColores2.colorSeleccionado);
                bufferGraphics2.fillOval(parseX2, parseY2, panelColores2.tam1, panelColores2.tam1);
                bufferGraphics2.fillOval(parseX, parseY, panelColores2.tam1, panelColores2.tam1);
                break;
            case 100 :
                //Goma
                //Funciona como el lapiz pero solo con el color blanco
                panelColores2.cambiaTamaño();
                bufferGraphics2.setColor(Color.WHITE);
                bufferGraphics2.fillOval(evt.getX(), evt.getY(), panelColores2.tam1, panelColores2.tam1);
                break;
            //Círculo
            case 1 : miCirculo.dibujante(bufferGraphics, evt.getX()); break;
            //Cuadrado
            case 4 : miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());break;
            //Pentágono
            case 5 : miForma.dibujante(bufferGraphics, evt.getX(), evt.getY()); break;
            //Triángulo
            case 3 : miForma.dibujante(bufferGraphics, evt.getX(), evt.getY()); break;
            //Estrella rara
            case 256 : miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());break;
            //Linea recta
            case 2 : miForma.dibujante(bufferGraphics, evt.getX(), evt.getY()); break;
                
            
        }
        repaint(0,0,1,1); 
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        switch(herramientas1.formaElegida){
            case 0 : break;
            //Dibuja el círculo del color seleccionado, con relleno o no, dependiendo de si está el checkbox seleccionado
            case 1 : miCirculo = new Circulo(evt.getX(), evt.getY(), 1, panelColores2.colorSeleccionado , herramientas1.relleno);
                     miCirculo.dibujante(bufferGraphics, evt.getX());
                break;
            //Dibuja el pentágono del color seleccionado, con relleno o no, dependiendo de si está el checkbox seleccionado
            case 5 : miForma = new Pentagono(evt.getX(), evt.getY(), 5, panelColores2.colorSeleccionado , herramientas1.relleno);
                     miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());
                break;
            //Dibuja el cuadrado del color seleccionado, con relleno o no, dependiendo de si está el checkbox seleccionado
            case 4 : miForma = new Cuadrado(evt.getX(), evt.getY(), 4, panelColores2.colorSeleccionado , herramientas1.relleno);
                     miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());
                break;
            //Dibuja el triángulo del color seleccionado, con relleno o no, dependiendo de si está el checkbox seleccionado
            case 3 : miForma = new Triangulo(evt.getX(), evt.getY(), 3, panelColores2.colorSeleccionado , herramientas1.relleno);
                     miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());
                break;
            //Dibuja la estrella del color seleccionado, con relleno o no, dependiendo de si está el checkbox seleccionado
            case 256 : miForma = new Estrella(evt.getX(), evt.getY(), 256, panelColores2.colorSeleccionado , herramientas1.relleno);
                     miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());
                break;
            //Dibuja la recta del color seleccionado, con relleno o no, dependiendo de si está el checkbox seleccionado
            case 2 : miForma = new Recta(evt.getX(), evt.getY(), 2, panelColores2.colorSeleccionado , false);
                     miForma.dibujante(bufferGraphics, evt.getX(), evt.getY());
                break;
            //Herramienta pipeta
            //Establece como color seleccionado el sitio donde pulses con esta herramienta
            case 314 : Color pipet = new Color(buffer2.getRGB(evt.getX(), evt.getY()));
                       panelColores2.colorSeleccionado = pipet;
                       panelColores2.bloque.setBackground(panelColores2.colorSeleccionado);
                break;
            //Herramienta de texto
            //Modifica el texto que va a aparecer donde tú des click
            //Se puede cambiar el tamaño, el color, si es cursiva/negrita/ambas/normal
            case 737 : bufferGraphics2.setColor(panelColores2.colorSeleccionado);
                       if(!herramientas1.cursiva && !herramientas1.negrita){
                           bufferGraphics2.setFont(new Font("TimesRoman", Font.PLAIN, herramientas1.tamText));
                       }
                       else if(!herramientas1.cursiva && herramientas1.negrita){
                           bufferGraphics2.setFont(new Font("TimesRoman", Font.BOLD, herramientas1.tamText));
                       }
                       else if(herramientas1.cursiva && !herramientas1.negrita){
                           bufferGraphics2.setFont(new Font("TimesRoman", Font.ITALIC, herramientas1.tamText));
                       }
                       else if(herramientas1.cursiva && herramientas1.negrita){
                           bufferGraphics2.setFont(new Font("TimesRoman", Font.ITALIC | Font.BOLD, herramientas1.tamText));
                       }
                       bufferGraphics2.drawString(herramientas1.textoEscrito, evt.getX(), evt.getY());
                break;
        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        //Si formaCont es falso las formas no se podrán dibujar
        if(herramientas1.formaCont){
            miForma.dibujante(bufferGraphics2, evt.getX(), evt.getY());
        }
        if(herramientas1.formaElegida == 1 && herramientas1.formaCont2){
            miCirculo.dibujante(bufferGraphics2, evt.getX());
        }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        jDialog1.setVisible(false);
        panelColores2.colorSeleccionado = jColorChooser1.getColor();
        panelColores2.bloque.setBackground(panelColores2.colorSeleccionado);
    }//GEN-LAST:event_guardarActionPerformed

    private void guardarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuActionPerformed
        int seleccion = jFileChooser1.showSaveDialog(this);
        if(seleccion == JFileChooser.APPROVE_OPTION){
            //si entra aquí es porque el usuario ha pulsado en "guardar"
            File fichero = jFileChooser1.getSelectedFile();
            String nombre = fichero.getName();
            String extension = nombre.substring(nombre.lastIndexOf('.')+1);
            if(extension.equalsIgnoreCase("jpg") || extension.equalsIgnoreCase("png")){
                try{
                ImageIO.write(buffer, "png", fichero);
                }
                catch (IOException e){
                }
            }
            else{
                //mensaje de extensión no válida
            }
            
        }
    }//GEN-LAST:event_guardarMenuActionPerformed
    
    private static int randomiz(int min, int max) {
	Random r = new Random();
	return r.nextInt((max - min) + 1) + min;
    }
    
    private void importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importarActionPerformed
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Imágenes JPG", "jpg"));
        jFileChooser1.setFileFilter(new FileNameExtensionFilter("Imágenes PNG", "png"));
        int seleccion = jFileChooser1.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION){
            File fichero = jFileChooser1.getSelectedFile();
            String nombre = fichero.getName();
            String extension = nombre.substring(nombre.lastIndexOf('.')+1, nombre.length());

            if (extension.equalsIgnoreCase("jpg") || extension.equalsIgnoreCase("png")) {
                try {
                    
                    bufferGraphics.drawImage(ImageIO.read(fichero), 0, 0, null);
                    bufferGraphics2.drawImage(ImageIO.read(fichero), 0, 0, null);
                    repaint(0,0,1,1);
                } catch (IOException ex) {
                }
            }
        }
    }//GEN-LAST:event_importarActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        inicializaBuffers();
    }//GEN-LAST:event_nuevoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialog3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        //Castea las coordenadas del ratón en strings para 
        //mostrarlas en los labels cordeX y cordeY
        String equis = Integer.toString(evt.getX());
        String yyy = Integer.toString(evt.getY());
        panelColores2.cordeX.setText("X: " + equis);
        panelColores2.cordeY.setText("Y: " + yyy);
    }//GEN-LAST:event_jPanel1MouseMoved
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoDtexto;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardar;
    private javax.swing.JMenuItem guardarMenu;
    private codigo.Herramientas herramientas1;
    private javax.swing.JMenuItem importar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem nuevo;
    private codigo.PanelColores panelColores2;
    // End of variables declaration//GEN-END:variables
}
